# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib foretaccess, .registration = TRUE
NULL

#' Version de la crate Rust `cablehelp` (noyau câble).
#'
#' Fonction triviale du Lot 0 : elle prouve que la chaîne R <-> Rust
#' (extendr) fonctionne de bout en bout. La mécanique CableHelp arrivera
#' au Lot 4 (voir specs/004-cable.md).
#' @export
cablehelp_version <- function() .Call(wrap__cablehelp_version)

# nolint end
