# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib foretaccess, .registration = TRUE
NULL

#' Version de la crate Rust `cablehelp` (noyau câble).
#'
#' Fonction triviale du Lot 0 : elle prouve que la chaîne R <-> Rust
#' (extendr) fonctionne de bout en bout. La mécanique CableHelp arrivera
#' au Lot 4 (voir specs/004-cable.md).
#' @export
cablehelp_version <- function() .Call(wrap__cablehelp_version)

#' Equation horizontale de la caténaire élastique `f_x(Th, Tv)`, nulle à la
#' solution.
#'
#' @param th Horizontal tension component at the upper support (N).
#' @param tv Vertical tension component at the upper support (N).
#' @param lo Unstretched cable length over the span (m).
#' @param eao Young's modulus times the cable section (N).
#' @param w Weight of the cable over its whole length (N).
#' @param f Gravity force of the load (N).
#' @param s1 Arc-length position of the load (m).
#' @param d Horizontal span between supports (m).
#' @return The horizontal residual (m); zero at the solution.
#' @export
cable_f_x <- function(th, tv, lo, eao, w, f, s1, d) .Call(wrap__cable_f_x, th, tv, lo, eao, w, f, s1, d)

#' Equation verticale de la caténaire élastique `f_z(Th, Tv)`, nulle à la
#' solution.
#'
#' @param th Horizontal tension component at the upper support (N).
#' @param tv Vertical tension component at the upper support (N).
#' @param lo Unstretched cable length over the span (m).
#' @param eao Young's modulus times the cable section (N).
#' @param w Weight of the cable over its whole length (N).
#' @param f Gravity force of the load (N).
#' @param s1 Arc-length position of the load (m).
#' @param h Altitude difference between supports (m).
#' @return The vertical residual (m); zero at the solution.
#' @export
cable_f_z <- function(th, tv, lo, eao, w, f, s1, h) .Call(wrap__cable_f_z, th, tv, lo, eao, w, f, s1, h)

#' Position horizontale du câble à l'abscisse curviligne `s`.
#'
#' @param th Horizontal tension component at the upper support (N).
#' @param tv Vertical tension component at the upper support (N).
#' @param lo Unstretched cable length over the span (m).
#' @param eao Young's modulus times the cable section (N).
#' @param w Weight of the cable over its whole length (N).
#' @param f Gravity force of the load (N).
#' @param s1 Arc-length position of the load (m).
#' @param s Arc-length position at which the cable is evaluated (m).
#' @return The horizontal position of the cable at `s` (m).
#' @export
cable_calcul_xs <- function(th, tv, lo, eao, w, f, s1, s) .Call(wrap__cable_calcul_xs, th, tv, lo, eao, w, f, s1, s)

#' Position verticale (chute depuis le support haut) à l'abscisse curviligne
#' `s` : c'est elle qui fournit la garde au sol du câble.
#'
#' @param th Horizontal tension component at the upper support (N).
#' @param tv Vertical tension component at the upper support (N).
#' @param lo Unstretched cable length over the span (m).
#' @param eao Young's modulus times the cable section (N).
#' @param w Weight of the cable over its whole length (N).
#' @param f Gravity force of the load (N).
#' @param s1 Arc-length position of the load (m).
#' @param s Arc-length position at which the cable is evaluated (m).
#' @return The vertical drop of the cable below the upper support at `s` (m).
#' @export
cable_calcul_zs <- function(th, tv, lo, eao, w, f, s1, s) .Call(wrap__cable_calcul_zs, th, tv, lo, eao, w, f, s1, s)

#' Amorçage `(Th, Tv, faisable)` par recherche sur grille sous la tension
#' admissible. Renvoie un vecteur de longueur 3 ; `faisable` vaut 1 si
#' `sqrt(Th^2 + Tv^2) <= tmax`, 0 sinon.
#'
#' @param tmax Admissible cable tension (N).
#' @param w Weight of the cable over its whole length (N).
#' @param eao Young's modulus times the cable section (N).
#' @param f Gravity force of the load (N).
#' @param pas Arc-length position of the load used for the grid seed (m).
#' @param d Horizontal span between supports (m).
#' @param h Altitude difference between supports (m).
#' @param lo Unstretched cable length over the span (m).
#' @param step Grid step in tension (N).
#' @return A length-3 numeric vector `c(Th, Tv, faisable)`.
#' @export
cable_find_thtv_tmax <- function(tmax, w, eao, f, pas, d, h, lo, step) .Call(wrap__cable_find_thtv_tmax, tmax, w, eao, f, pas, d, h, lo, step)

#' Résout `f_x = f_z = 0` (tensions `Th, Tv` au support haut) par
#' Newton-Raphson à Jacobien analytique, repli sur grille. Renvoie un vecteur
#' `c(Th, Tv)`.
#'
#' @param th Initial guess for the horizontal tension component (N).
#' @param tv Initial guess for the vertical tension component (N).
#' @param h_alt Altitude difference between supports (m).
#' @param d Horizontal span between supports (m).
#' @param lo Unstretched cable length over the span (m).
#' @param w Weight of the cable over its whole length (N).
#' @param s1 Arc-length position of the load (m).
#' @param f Gravity force of the load (N).
#' @param eao Young's modulus times the cable section (N).
#' @param tmax Admissible cable tension (N), bounding the grid fallback.
#' @param err Tolerance on the Newton step (N).
#' @return A length-2 numeric vector `c(Th, Tv)`.
#' @export
cable_newton_thtv <- function(th, tv, h_alt, d, lo, w, s1, f, eao, tmax, err) .Call(wrap__cable_newton_thtv, th, tv, h_alt, d, lo, w, s1, f, eao, tmax, err)

#' Pré-filtre géométrique : le câble est approximé par la corde entre supports
#' moins une flèche analytique. Renvoie 1 si le profil `(line_x, line_z)` reste
#' dans les gardes entre les indices `pg+1` et `pd-1`, 0 sinon. Sans supports
#' intermédiaires (Lot 4b).
#'
#' @param fact Direction of the line (+1 or -1).
#' @param h_alt Altitude difference between supports (m).
#' @param d Horizontal span between supports (m).
#' @param xup Horizontal position of the upper support (m).
#' @param zup Altitude of the upper support (m).
#' @param line_x Horizontal positions along the terrain profile (m).
#' @param line_z Altitudes of the terrain profile (m).
#' @param hline_min Minimum ground clearance of the cable (m).
#' @param hline_max Maximum height of the cable (m).
#' @param tmax Admissible cable tension (N).
#' @param q1 Linear mass of the skyline (kg/m).
#' @param q2 Linear mass of the mainline / traction cable (kg/m).
#' @param q3 Linear mass of the return cable (kg/m).
#' @param f_o Gravity force of the load and carriage (N).
#' @param pg Index of the near support in the profile.
#' @param pd Index of the far support in the profile.
#' @return 1 if the span passes the pre-filter, 0 otherwise.
#' @export
cable_check_droite <- function(fact, h_alt, d, xup, zup, line_x, line_z, hline_min, hline_max, tmax, q1, q2, q3, f_o, pg, pd) .Call(wrap__cable_check_droite, fact, h_alt, d, xup, zup, line_x, line_z, hline_min, hline_max, tmax, q1, q2, q3, f_o, pg, pd)

#' Faisabilité complète d'une travée : la charge balaie la longueur, on résout
#' les tensions à chaque position et on mesure la garde au sol. Renvoie la
#' garde minimale rencontrée (m), ou `-1` si la travée est infaisable (garde
#' hors `[hline_min, hline_max]` ou tension au-delà de `tmax + 1000`). Sans
#' supports intermédiaires (Lot 4b).
#'
#' @param alts Terrain altitudes under the line, sampled every 0.5 m (m).
#' @param h_alt Altitude difference between supports (m).
#' @param d Horizontal span between supports (m).
#' @param lo Unstretched cable length over the span (m).
#' @param fact Direction of the line (+1 or -1).
#' @param tho Horizontal tension with the load centred (N).
#' @param tvo Vertical tension with the load centred (N).
#' @param xup Horizontal position of the upper support (m).
#' @param zup Altitude of the upper support (m).
#' @param f_o Gravity force of the load and carriage (N).
#' @param tmax Admissible cable tension (N).
#' @param hline_min Minimum ground clearance of the cable (m).
#' @param hline_max Maximum height of the cable (m).
#' @param q1 Linear mass of the skyline (kg/m).
#' @param q2 Linear mass of the mainline / traction cable (kg/m).
#' @param q3 Linear mass of the return cable (kg/m).
#' @param csize Sweep step of the load position (m).
#' @param eao Young's modulus times the cable section (N).
#' @return The minimum ground clearance (m), or `-1` if infeasible.
#' @export
cable_check_hlinemin <- function(alts, h_alt, d, lo, fact, tho, tvo, xup, zup, f_o, tmax, hline_min, hline_max, q1, q2, q3, csize, eao) .Call(wrap__cable_check_hlinemin, alts, h_alt, d, lo, fact, tho, tvo, xup, zup, f_o, tmax, hline_min, hline_max, q1, q2, q3, csize, eao)

# nolint end
